### ISSUE TITLE
Add license (MIT or BSD)

### ISSUE THREAD

**Issue by pdhahn** [arntanguy/sgsmooth#1]
Please add a license file for this code. Use MIT or BSD license so this code can be used without issue in any kind of application, including commercial.

**Comment by arntanguy** [comment]
I do not own this code, I've only taken it from raw public code online, and packaged it in a sensible manner.
I recommend you use my Gram Savitzky-Golay implementation instead, as it's much simpler, more efficient, and I wrote it: https://github.com/arntanguy/gram_savitzky_golay
