### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fweinzerl** [arntanguy/sgsmooth#2]
Hello,

please consider adding a license file to this repo.
I would really like to use your library.

Have a good day!

**Comment by arntanguy** [comment]
Unfortunately, I do not own this code, I've only taken it from raw public code online, and packaged it in a sensible manner. I recommend you use my Gram Savitzky-Golay implementation instead, as it's much simpler, more efficient, and I wrote it: https://github.com/arntanguy/gram_savitzky_golay
It is currently licenced under LGPL3, but I wouldn't mind relicening it under BSD2 if that's more suitable to your needs.

**Comment by fweinzerl** [comment]
I saw the other issue too late, that is why I closed this one. Sorry for the mess in your Issues section.
LGPL3 is fine for me, thanks for the offer.

**Comment by arntanguy** [comment]
No problem.
